[workspace]
types = "app/src/lib/types"

[features]
seeds = false
skip-lint = false
[programs.localnet]
workshop_solana_lottery = "1o2BymoRfoCwBnW2qr2oDjtqjhpNPA3JBj6tgk8raVf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
